/* Datos de provincias romanas para el juego "Silueta Imperial". */
window.PROVINCIAS_DATA = [
  { id:'britannia', x:280, y:230, nombre:'Britannia', region:'Britania e Islas', tipo:'Imperial',
    paisModerno:'Reino Unido', capitalModerna:'Londres', capitalRomana:'Londinium', sigloAnexion:'Siglo I d.C.',
    dato:'Conquistada por el emperador Claudio en el 43 d.C.' },
  { id:'belgica', x:403, y:300, nombre:'Gallia Belgica', region:'Galia y Germania', tipo:'Imperial',
    paisModerno:'Bélgica', capitalModerna:'Bruselas', capitalRomana:'Durocortorum (Reims)', sigloAnexion:'Siglo I a.C.',
    dato:'Su nombre sobrevive hoy en "Bélgica".' },
  { id:'germania_inferior', x:435, y:300, nombre:'Germania Inferior', region:'Galia y Germania', tipo:'Imperial',
    paisModerno:'Alemania', capitalModerna:'Berlín', capitalRomana:'Colonia Agrippina (Colonia)', sigloAnexion:'Siglo I d.C.',
    dato:'La ciudad de Colonia lleva el nombre de esta "Colonia" romana.' },
  { id:'germania_superior', x:465, y:355, nombre:'Germania Superior', region:'Galia y Germania', tipo:'Imperial',
    paisModerno:'Alemania', capitalModerna:'Berlín', capitalRomana:'Moguntiacum (Maguncia)', sigloAnexion:'Siglo I d.C.',
    dato:'Protegida por el limes germánico, una larga frontera fortificada.' },
  { id:'lugdunensis', x:330, y:350, nombre:'Gallia Lugdunensis', region:'Galia y Germania', tipo:'Imperial',
    paisModerno:'Francia', capitalModerna:'París', capitalRomana:'Lugdunum (Lyon)', sigloAnexion:'Siglo I a.C.',
    dato:'Lugdunum fue la capital administrativa de las tres Galias.' },
  { id:'aquitania', x:283, y:400, nombre:'Gallia Aquitania', region:'Galia y Germania', tipo:'Imperial',
    paisModerno:'Francia', capitalModerna:'París', capitalRomana:'Burdigala (Burdeos)', sigloAnexion:'Siglo I a.C.',
    dato:'Dio nombre a la región francesa de Aquitania.' },
  { id:'narbonensis', x:330, y:465, nombre:'Gallia Narbonensis', region:'Galia y Germania', tipo:'Senatorial',
    paisModerno:'Francia', capitalModerna:'París', capitalRomana:'Narbo (Narbona)', sigloAnexion:'Siglo II a.C.',
    dato:'La primera provincia romana establecida fuera de Italia en la Galia.' },
  { id:'raetia', x:500, y:390, nombre:'Raetia', region:'Galia y Germania', tipo:'Imperial',
    paisModerno:'Suiza', capitalModerna:'Berna', capitalRomana:'Curia (Coira)', sigloAnexion:'Siglo I a.C.',
    dato:'Cubría buena parte de los Alpes centrales.' },
  { id:'noricum', x:554, y:392, nombre:'Noricum', region:'Galia y Germania', tipo:'Imperial',
    paisModerno:'Austria', capitalModerna:'Viena', capitalRomana:'Virunum', sigloAnexion:'Siglo I a.C.',
    dato:'Anexada pacíficamente, sin conquista militar, hacia el 15 a.C.' },
  { id:'pannonia_superior', x:583, y:440, nombre:'Pannonia Superior', region:'Danubio y los Balcanes', tipo:'Imperial',
    paisModerno:'Austria', capitalModerna:'Viena', capitalRomana:'Carnuntum', sigloAnexion:'Siglo I d.C.',
    dato:'Frontera clave del Danubio frente a los pueblos germánicos.' },
  { id:'pannonia_inferior', x:629, y:447, nombre:'Pannonia Inferior', region:'Danubio y los Balcanes', tipo:'Imperial',
    paisModerno:'Hungría', capitalModerna:'Budapest', capitalRomana:'Aquincum', sigloAnexion:'Siglo I d.C.',
    dato:'Aquincum, su capital, ocupaba lo que hoy es Budapest.' },
  { id:'dalmatia', x:580, y:470, nombre:'Dalmatia', region:'Danubio y los Balcanes', tipo:'Imperial',
    paisModerno:'Croacia', capitalModerna:'Zagreb', capitalRomana:'Salona', sigloAnexion:'Siglo I d.C.',
    dato:'El emperador Diocleciano nació aquí y se retiró a un palacio en Split.' },
  { id:'dacia', x:700, y:470, nombre:'Dacia', region:'Danubio y los Balcanes', tipo:'Imperial',
    paisModerno:'Rumania', capitalModerna:'Bucarest', capitalRomana:'Sarmizegetusa', sigloAnexion:'Siglo II d.C.',
    dato:'Conquistada por Trajano; abandonada por Aureliano en el 271 d.C.' },
  { id:'moesia_superior', x:670, y:520, nombre:'Moesia Superior', region:'Danubio y los Balcanes', tipo:'Imperial',
    paisModerno:'Serbia', capitalModerna:'Belgrado', capitalRomana:'Naissus (Niš)', sigloAnexion:'Siglo I d.C.',
    dato:'Naissus fue la ciudad natal del emperador Constantino I.' },
  { id:'moesia_inferior', x:770, y:465, nombre:'Moesia Inferior', region:'Danubio y los Balcanes', tipo:'Imperial',
    paisModerno:'Rumania', capitalModerna:'Bucarest', capitalRomana:'Tomis (Constanța)', sigloAnexion:'Siglo I d.C.',
    dato:'El poeta Ovidio murió en el exilio en Tomis.' },
  { id:'thracia', x:760, y:545, nombre:'Thracia', region:'Grecia y los Balcanes', tipo:'Imperial',
    paisModerno:'Bulgaria', capitalModerna:'Sofía', capitalRomana:'Philippopolis (Plovdiv)', sigloAnexion:'Siglo I d.C.',
    dato:'Anexada como provincia recién en el 46 d.C., bajo Claudio.' },
  { id:'macedonia', x:690, y:575, nombre:'Macedonia', region:'Grecia y los Balcanes', tipo:'Senatorial',
    paisModerno:'Grecia', capitalModerna:'Atenas', capitalRomana:'Thessalonica (Salónica)', sigloAnexion:'Siglo II a.C.',
    dato:'Cuna del imperio de Alejandro Magno, siglos antes de Roma.' },
  { id:'epirus', x:645, y:600, nombre:'Epirus', region:'Grecia y los Balcanes', tipo:'Senatorial',
    paisModerno:'Grecia', capitalModerna:'Atenas', capitalRomana:'Nicopolis', sigloAnexion:'Siglo II a.C.',
    dato:'Nicópolis fue fundada por Augusto para celebrar su victoria en Actio.' },
  { id:'achaia', x:711, y:620, nombre:'Achaia', region:'Grecia y los Balcanes', tipo:'Senatorial',
    paisModerno:'Grecia', capitalModerna:'Atenas', capitalRomana:'Corinthus (Corinto)', sigloAnexion:'Siglo II a.C.',
    dato:'Incluía a Atenas, todavía un gran centro cultural bajo Roma.' },
  { id:'italia', x:520, y:520, nombre:'Italia', region:'Italia y el Mediterráneo occidental', tipo:'Senatorial',
    paisModerno:'Italia', capitalModerna:'Roma', capitalRomana:'Roma', sigloAnexion:'Siglo VIII a.C.',
    dato:'No era una "provincia" común: era el corazón mismo del Imperio.' },
  { id:'corsica_et_sardinia', x:436, y:527, nombre:'Corsica et Sardinia', region:'Italia y el Mediterráneo occidental', tipo:'Senatorial',
    paisModerno:'Italia', capitalModerna:'Roma', capitalRomana:'Caralis (Cagliari)', sigloAnexion:'Siglo III a.C.',
    dato:'Dos islas administradas como una sola provincia.' },
  { id:'sicilia', x:557, y:658, nombre:'Sicilia', region:'Italia y el Mediterráneo occidental', tipo:'Senatorial',
    paisModerno:'Italia', capitalModerna:'Roma', capitalRomana:'Syracusae (Siracusa)', sigloAnexion:'Siglo III a.C.',
    dato:'La primera provincia romana de todas, tras la Primera Guerra Púnica.' },
  { id:'tarraconensis', x:200, y:470, nombre:'Hispania Tarraconensis', region:'Hispania', tipo:'Imperial',
    paisModerno:'España', capitalModerna:'Madrid', capitalRomana:'Tarraco (Tarragona)', sigloAnexion:'Siglo I a.C.',
    dato:'La provincia hispana más extensa, con capital en Tarraco.' },
  { id:'lusitania', x:100, y:520, nombre:'Lusitania', region:'Hispania', tipo:'Imperial',
    paisModerno:'España', capitalModerna:'Madrid', capitalRomana:'Emerita Augusta (Mérida)', sigloAnexion:'Siglo I a.C.',
    dato:'Su capital, Emerita Augusta, conserva uno de los mejores teatros romanos.' },
  { id:'baetica', x:150, y:580, nombre:'Baetica', region:'Hispania', tipo:'Senatorial',
    paisModerno:'España', capitalModerna:'Madrid', capitalRomana:'Corduba (Córdoba)', sigloAnexion:'Siglo I a.C.',
    dato:'Cuna de Trajano y Adriano, los primeros emperadores nacidos fuera de Italia.' },
  { id:'mauretania_tingitana', x:103, y:660, nombre:'Mauretania Tingitana', region:'África del Norte', tipo:'Imperial',
    paisModerno:'Marruecos', capitalModerna:'Rabat', capitalRomana:'Tingis (Tánger)', sigloAnexion:'Siglo I d.C.',
    dato:'El extremo occidental del norte de África romano.' },
  { id:'mauretania_caesariensis', x:233, y:665, nombre:'Mauretania Caesariensis', region:'África del Norte', tipo:'Imperial',
    paisModerno:'Argelia', capitalModerna:'Argel', capitalRomana:'Caesarea (Cherchell)', sigloAnexion:'Siglo I d.C.',
    dato:'Antiguo reino cliente anexado por Claudio en el 44 d.C.' },
  { id:'africa_proconsularis', x:394, y:660, nombre:'Africa Proconsularis', region:'África del Norte', tipo:'Senatorial',
    paisModerno:'Túnez', capitalModerna:'Túnez', capitalRomana:'Carthago (Cartago)', sigloAnexion:'Siglo II a.C.',
    dato:'Levantada sobre las ruinas de la Cartago destruida en el 146 a.C.' },
  { id:'cyrenaica_et_creta', x:733, y:764, nombre:'Cyrenaica et Creta', region:'África del Norte', tipo:'Senatorial',
    paisModerno:'Libia', capitalModerna:'Trípoli', capitalRomana:'Cyrene', sigloAnexion:'Siglo I a.C.',
    dato:'Unía una región de Libia con la isla griega de Creta.' },
  { id:'aegyptus', x:856, y:830, nombre:'Aegyptus', region:'África del Norte', tipo:'Imperial',
    paisModerno:'Egipto', capitalModerna:'El Cairo', capitalRomana:'Alexandria', sigloAnexion:'Siglo I a.C.',
    dato:'Provincia personal del emperador: ningún senador podía visitarla sin permiso.' },
  { id:'bithynia_et_pontus', x:850, y:575, nombre:'Bithynia et Pontus', region:'Anatolia y el Egeo', tipo:'Senatorial',
    paisModerno:'Turquía', capitalModerna:'Ankara', capitalRomana:'Nicomedia (İzmit)', sigloAnexion:'Siglo I a.C.',
    dato:'Plinio el Joven la gobernó y escribió a Trajano sobre los cristianos.' },
  { id:'asia', x:827, y:626, nombre:'Asia', region:'Anatolia y el Egeo', tipo:'Senatorial',
    paisModerno:'Turquía', capitalModerna:'Ankara', capitalRomana:'Ephesus (Éfeso)', sigloAnexion:'Siglo II a.C.',
    dato:'Una de las provincias más ricas del Imperio.' },
  { id:'cappadocia', x:975, y:595, nombre:'Cappadocia', region:'Anatolia y el Egeo', tipo:'Imperial',
    paisModerno:'Turquía', capitalModerna:'Ankara', capitalRomana:'Caesarea (Kayseri)', sigloAnexion:'Siglo I d.C.',
    dato:'Región de paisajes volcánicos, anexada bajo Tiberio.' },
  { id:'cilicia', x:940, y:660, nombre:'Cilicia', region:'Anatolia y el Egeo', tipo:'Imperial',
    paisModerno:'Turquía', capitalModerna:'Ankara', capitalRomana:'Tarsus (Tarso)', sigloAnexion:'Siglo I a.C.',
    dato:'Tarso, su capital, fue la ciudad natal de San Pablo.' },
  { id:'lycia_et_pamphylia', x:880, y:655, nombre:'Lycia et Pamphylia', region:'Anatolia y el Egeo', tipo:'Imperial',
    paisModerno:'Turquía', capitalModerna:'Ankara', capitalRomana:'Attaleia (Antalya)', sigloAnexion:'Siglo I d.C.',
    dato:'Costa mediterránea famosa por sus ciudades-estado licias.' },
  { id:'cyprus', x:923, y:705, nombre:'Cyprus', region:'Anatolia y el Egeo', tipo:'Senatorial',
    paisModerno:'Chipre', capitalModerna:'Nicosia', capitalRomana:'Salamis', sigloAnexion:'Siglo I a.C.',
    dato:'Gobernada por un procónsul; Pablo y Bernabé predicaron allí.' },
  { id:'syria', x:987, y:666, nombre:'Syria', region:'El Levante', tipo:'Imperial',
    paisModerno:'Siria', capitalModerna:'Damasco', capitalRomana:'Antiochia (Antioquía)', sigloAnexion:'Siglo I a.C.',
    dato:'Antioquía fue la tercera ciudad más grande del Imperio.' },
  { id:'iudaea', x:972, y:768, nombre:'Iudaea', region:'El Levante', tipo:'Senatorial',
    paisModerno:'Israel', capitalModerna:'Jerusalén', capitalRomana:'Caesarea Maritima', sigloAnexion:'Siglo I d.C.',
    dato:'Gobernada por prefectos como Poncio Pilato; luego rebautizada Syria Palaestina.' },
  { id:'arabia_petraea', x:985, y:805, nombre:'Arabia Petraea', region:'El Levante', tipo:'Imperial',
    paisModerno:'Jordania', capitalModerna:'Amán', capitalRomana:'Bostra', sigloAnexion:'Siglo II d.C.',
    dato:'Incorporó el antiguo reino nabateo de Petra, anexado en el 106 d.C.' },
  { id:'armenia', x:1080, y:532, nombre:'Armenia', region:'Armenia y Mesopotamia', tipo:'Imperial',
    paisModerno:'Armenia', capitalModerna:'Ereván', capitalRomana:'Artaxata', sigloAnexion:'Siglo II d.C.',
    dato:'Provincia efímera de Trajano: sus sucesores la abandonaron enseguida.' },
  { id:'mesopotamia', x:1082, y:636, nombre:'Mesopotamia', region:'Armenia y Mesopotamia', tipo:'Imperial',
    paisModerno:'Irak', capitalModerna:'Bagdad', capitalRomana:'Nisibis', sigloAnexion:'Siglo II d.C.',
    dato:'La conquista más oriental de Roma, entre el Tigris y el Éufrates.' },
  { id:'assyria', x:1140, y:610, nombre:'Assyria', region:'Armenia y Mesopotamia', tipo:'Imperial',
    paisModerno:'Irak', capitalModerna:'Bagdad', capitalRomana:'Ctesiphon', sigloAnexion:'Siglo II d.C.',
    dato:'Llegó hasta la capital parta, Ctesifonte, en el punto más extremo del Imperio.' }
];

/* Datos del país moderno de cada provincia, para las preguntas del modo fácil. */
window.PAISES_INFO = {
  'Reino Unido': { continente:'Europa', idioma:'inglés', moneda:'libra esterlina', bandera:'🇬🇧' },
  'Bélgica': { continente:'Europa', idioma:'neerlandés y francés', moneda:'euro', bandera:'🇧🇪' },
  'Alemania': { continente:'Europa', idioma:'alemán', moneda:'euro', bandera:'🇩🇪' },
  'Francia': { continente:'Europa', idioma:'francés', moneda:'euro', bandera:'🇫🇷' },
  'Suiza': { continente:'Europa', idioma:'alemán, francés e italiano', moneda:'franco suizo', bandera:'🇨🇭' },
  'Austria': { continente:'Europa', idioma:'alemán', moneda:'euro', bandera:'🇦🇹' },
  'Hungría': { continente:'Europa', idioma:'húngaro', moneda:'florín húngaro', bandera:'🇭🇺' },
  'Croacia': { continente:'Europa', idioma:'croata', moneda:'euro', bandera:'🇭🇷' },
  'Rumania': { continente:'Europa', idioma:'rumano', moneda:'leu rumano', bandera:'🇷🇴' },
  'Serbia': { continente:'Europa', idioma:'serbio', moneda:'dinar serbio', bandera:'🇷🇸' },
  'Bulgaria': { continente:'Europa', idioma:'búlgaro', moneda:'lev búlgaro', bandera:'🇧🇬' },
  'Grecia': { continente:'Europa', idioma:'griego', moneda:'euro', bandera:'🇬🇷' },
  'Italia': { continente:'Europa', idioma:'italiano', moneda:'euro', bandera:'🇮🇹' },
  'España': { continente:'Europa', idioma:'español', moneda:'euro', bandera:'🇪🇸' },
  'Marruecos': { continente:'África', idioma:'árabe y bereber', moneda:'dírham marroquí', bandera:'🇲🇦' },
  'Argelia': { continente:'África', idioma:'árabe', moneda:'dinar argelino', bandera:'🇩🇿' },
  'Túnez': { continente:'África', idioma:'árabe', moneda:'dinar tunecino', bandera:'🇹🇳' },
  'Libia': { continente:'África', idioma:'árabe', moneda:'dinar libio', bandera:'🇱🇾' },
  'Egipto': { continente:'África', idioma:'árabe', moneda:'libra egipcia', bandera:'🇪🇬' },
  'Turquía': { continente:'Asia', idioma:'turco', moneda:'lira turca', bandera:'🇹🇷' },
  'Chipre': { continente:'Asia', idioma:'griego y turco', moneda:'euro', bandera:'🇨🇾' },
  'Siria': { continente:'Asia', idioma:'árabe', moneda:'libra siria', bandera:'🇸🇾' },
  'Israel': { continente:'Asia', idioma:'hebreo y árabe', moneda:'séquel nuevo israelí', bandera:'🇮🇱' },
  'Jordania': { continente:'Asia', idioma:'árabe', moneda:'dinar jordano', bandera:'🇯🇴' },
  'Armenia': { continente:'Asia', idioma:'armenio', moneda:'dram armenio', bandera:'🇦🇲' },
  'Irak': { continente:'Asia', idioma:'árabe y kurdo', moneda:'dinar iraquí', bandera:'🇮🇶' }
};
